spring:
  thymeleaf:
    cache: false
  datasource:
    name: dataSource
    url: jdbc:mysql://localhost:3306/db_aty?useSSL=false&characterEncoding=utf8
    username: root
    password: ENCRYPT#QHglRXNZGLY=
    driver-class-name: com.mysql.jdbc.Driver

